-- This module contains some commands that should be executed on each startup
-- Note: some commands may conflict with "auto-session" plugin, so it is recommended
-- to execute ALL command from config in "lua/plugins/auto-session.lua"
